from rsf.proj import *

ft2km = 0.3048
d1 = 0.0250
o2 =10.025
d2 =0.0375

Flow('vel','sigsbee2a_migvel.sgy',
     '''
     segyread read=data |
     scale rscale=0.001 |
     scale rscale=%g |
     put label=Velocity unit=m/s
     o1=0  d1=%g label1=Depth    unit1=m
     o2=%g d2=%g label2=Distance unit2=m
     ''' % (ft2km,d1*ft2km,o2*ft2km,d2*ft2km))
Flow('vel_resampled','vel',
     '''
     transp plane=12 | 
     sfsinc n1=500 o1=3.32994 d1=0.04572 |
     transp plane=12
     ''')

Flow('v','vel_resampled',
     '''
     put d1=7.62 o1=0 |
     put d2=45.72 o2=3329.94 |
     math output="input*1000"
     ''')
Flow('d','zodata',
     '''
     put d2=45.72 o2=3329.94 unit2=m 
     ''')
Plot('d','grey scalebar=y ')
Plot('v','grey color=j allpos=y bias=1.5 scalebar=y barreverse=y wanttitle=n')

Flow('dmig_PSPI','d v', 
     '''
     PSPI_split_step_post_stack fmin=2 fmax=35 Number_of_reference_vel=5 option=1
     velfile=${SOURCES[1]}
     ''')
Plot('dmig_PSPI','grey scalebar=y label1="Depth" unit1="m" label2="Distance" unit2="m" title="Post-stack PSPI Migrated Image" wanttitle=y')

Flow('dmig_SS','d v', 
     '''
     PSPI_split_step_post_stack fmin=2 fmax=30 Number_of_reference_vel=2 option=2
     velfile=${SOURCES[1]}
     ''')
Plot('dmig_SS','grey scalebar=y label1="Depth" unit1="m" label2="Distance" unit2="m" title="Post-stack Split_Step Migrated Image" wanttitle=y')

Result('results','d dmig_PSPI dmig_SS v','SideBySideAniso')
End()